### ISSUE TITLE
Add compatibility with Potions Plus mods

### ISSUE THREAD

**Issue by Mycc0985** [Wufflez/Loki#11]
Add compatibility with Potions Plus mods, And his Alchemy skill
Gives an error if the character gets this skill.
The program will not be able to open the character file)

https://www.nexusmods.com/valheim/mods/1561

**Comment by BrandonT80** [comment]
I created a pull request that fixes this issue at least temporarily. While it does not directly make it compatible it at least allows use of the program without having the plugin break it.

**Comment by BrandonT80** [comment]
> Add compatibility with Potions Plus mods, And his Alchemy skill Gives an error if the character gets this skill. The program will not be able to open the character file)
> 
> https://www.nexusmods.com/valheim/mods/1561

If you need a working release, my fork has the pull request completed and released for use. Just until the request is added.

**Comment by Mycc0985** [comment]
> I created a pull request that fixes this issue at least temporarily. While it does not directly make it compatible it at least allows use of the program without having the plugin break it.

Can you give me a compiled version ? And then I have a problem with vs22

**Comment by BrandonT80** [comment]
> > I created a pull request that fixes this issue at least temporarily. While it does not directly make it compatible it at least allows use of the program without having the plugin break it.
> 
> Can you give me a compiled version ? And then I have a problem with vs22

The newest version (0.9.0) has this implemented now. My newest pull request does have compatibility for Potions Plus but I am not around to send over a compiled version for that. For Potions Plus, the bottom-most skill is the one for that plugin. It shows up as "Unknown" but it is always going to be the last one because they use 25,000 or something as its ID when everything else is 700-900. 

That version is here:
https://github.com/Wufflez/Loki/releases/tag/v0.9-beta
